### ISSUE TITLE
Add cli support 

### ISSUE THREAD

**Issue by fregante** [erikdesjardins/firefox-extension-deploy#10]
It'd be nice to be able to upload an extension via command line like [chrome-webstore-upload](https://github.com/DrewML/chrome-webstore-upload-cli) does. 

For example:
```sh
$ firefox-extension-deploy ./extension
```

**Comment by erikdesjardins** [comment]
If you want a CLI you should use [`jpm sign`](https://github.com/mozilla-jetpack/jpm) or [`web-ext sign`](https://github.com/mozilla/web-ext); this only exists because they don't have a (documented) JS API. (perhaps I should document that)

**Comment by fregante** [comment]
"This is a command line tool to help build, run, and test web extensions."

They have different purposes. web-ext's signing feature is only for self-hosting, it doesn't handle deployment.

**Comment by erikdesjardins** [comment]
No, the documentation is misleading. If you use it to "sign" a public addon on AMO, it submits the addon for review. I've done it.

**Comment by erikdesjardins** [comment]
More info: AMO's addon API [has just four endpoints related to submission/signing](http://addons-server.readthedocs.io/en/latest/topics/api/signing.html), and the same one is used for submitting public addons and signing self-hosted addons.

`web-ext sign` [internally](https://github.com/mozilla/web-ext/blob/7a44860c2bbf77ce610a63719aa8147cdb51d66d/src/cmd/sign.js#L99-L110) uses `sign-addon`, which [explicitly handles](https://github.com/mozilla/sign-addon/blob/b368d3ec19c64990501715cf11cde229ce5d7a3b/src/amo-client.js#L176) addons requiring manual review.

Edit: also, though the `jpm sign` [docs](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign) begin with:

> This allows you to self-host your add-on

just a bit further down, they list:

> - You add-on passed validation but it could not be automatically signed because your add-on is listed. Listed add-ons will require a manual review before they can be signed.

Edit 2: Even [the docs](http://addons-server.readthedocs.io/en/latest/topics/api/signing.html#client-libraries) for the endpoint this repo uses suggest to use `jpm sign`:

> If you are developing an add-on using the Add-on SDK, you may wish to use the jpm sign command to interact with the signing API.

**Comment by fregante** [comment]
Thank you! Appreciated. I'll give it a go

**Comment by fregante** [comment]
Excellent! I tried and it did upload it, even though it [exited with non-0](http://i.imgur.com/W4QR63l.png)

Wouldn't it make sense for `firefox-extension-deploy` to be a wrapper around `web-ext` at this point? They do export `main.js` and it looks like it accepts an object just like `firefox-extension-deploy`

Also: https://github.com/mozilla/web-ext/issues/683
